version: '3.9'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: cache
    hostname: cache
    ports:
      - 6379:6379
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --port 6379
    volumes: 
      - cache:/data
    networks:
      - antidote
  backend:
    restart: unless-stopped
    ports: 
      - 3000:3000
    build:
      context: backend
      dockerfile: ./Dockerfile
      args:
        - PORT=3000
        - API_KEY=6939a943cde04da5996776f1789673e0
        - REDIS_EXPIRE_TIME=80000
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - antidote
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports: 
      - 4200:4200
    expose: 
      - 4200
    depends_on:
      - backend
networks:
  antidote:
    name: antidote_network
    driver: bridge
volumes:
  cache:
    driver: local